= PostgreSQL for midPoint

Before running `vagrant up` first create `tmp` directory for non-provided files.
TODO: currently not needed for new repo.
Create Vagrantbox, then initialize it manually (e.g. from IDE).
User `midpoint` will be created.

//Following files from midpoint sources (repository) go to `tmp` directory:

//* https://raw.githubusercontent.com/Evolveum/midpoint/master/config/sql/postgresql-4.2-all.sql
//* https://raw.githubusercontent.com/Evolveum/midpoint/master/repo/repo-sql-impl-test/sql-procedures/postgresql.sql

Then run:
----
vagrant up
----

And wait... if everything is OK, you can try:
----
vagrant ssh
----

== How to use

JDBC URL is: `jdbc:postgresql://192.168.56.33:5432/midpoint`

Username/password: `midpoint`/`password`

IP must match the one from the link:Vagrantfile[].

Properties file `vagrant-postgresql.properties` for tests is provided, see comment there how to use it.

Just copy provided `config.xml` (not used by the Vagrant box, actually) to your `${midpoint.home}`.
Alternatively, create a new directory like `midpoint-home-postgresql`, put the `config.xml` there
and run the midpoint with this JVM argument: `-Dmidpoint.home=<path-to>\midpoint-home-posgresql`.

== See also

https://wiki.evolveum.com/display/midPoint/PostgreSQL
