= PostgreSQL for midPoint - new repository

Necessary SQL schema files from midpoint sources (repository) are downloaded by Vagrantfile.
If a different version is necessary, modify the `Vagrantfile` accordingly.

To run the environment (first time takes longer):

----
vagrant up
----

And wait... if everything is OK, you can try:

----
vagrant ssh
----

[IMPORTANT]
====
Main reason for this Vagrantbox is testing with new repository - that's what `midpoint` database
is for; for automated tests with new repo there is separate `midtest` database too.

But there is also `midold` database with old repository which is also available with another
Vagrantbox - why is it here?
It's meant for comparison tests on the same "hardware" with the same PG version and setup.
You can ignore it if you're only interested in the new repository.
====

== How to use

JDBC URL is: `jdbc:postgresql://192.168.56.33:5432/midpoint`

Username/password: `midpoint`/`password`

Alternative databases (password is the same as above):

* for automated tests - database and username `midtest`
* old repository for comparison tests - database and username `midold`

IP must match the one from the link:Vagrantfile[].

Properties file `vagrant-midtest.properties` for tests is provided, see comment there how to use it.
Use it with the following JVM argument:
----
-Dconfig=<path-to-vagrantboxes>/vagrant-midpoint-db-pg-new-repo/vagrant-midtest.properties
----

Config file for old repository can be used in a similar way.

To use the new repository for midpoint application it is recommended to pre-create dedicated
`${midpoint.home}` directory for it and copy the provided `config.xml` there.
Then run the midpoint with this JVM argument: `-Dmidpoint.home=<path-to>\midpoint-home-pgnew`
(where `midpoint-home-pgnew` is the actual midPoint home).

== See also

* https://docs.evolveum.com/midpoint/projects/midscale/design/repo/new-repo-startup/[How to start with new repository]
* https://wiki.evolveum.com/display/midPoint/PostgreSQL[Postgres setup for old repository]
