= midPoint support Vagrant boxes


|===
| Vagrantbox | IP | Notes

3+| *Database boxes*
| vagrant-midpoint-db-postgresql | 192.168.56.30
| link:vagrant-midpoint-db-postgresql/README.adoc[PostgreSQL]
| vagrant-midpoint-db-oracle-xe | 192.168.56.31
| link:vagrant-midpoint-db-oracle-xe/README.adoc[Oracle XE 18c]
| vagrant-midpoint-db-mariadb | 192.168.56.32
| link:vagrant-midpoint-db-mariadb/README.adoc[MariaDB]
| vagrant-midpoint-db-pg-new-repo | 192.168.56.33
| link:vagrant-midpoint-db-pg-new-repo/README.adoc[PostgreSQL 13] WIP for midScale

3+| *midPoint boxes*
| vagrant-midpoint (TODO) | 192.168.56.40
|
| vagrant-midpoint-linux-build | 192.168.56.50 
| link:vagrant-midpoint-linux-build/README.adoc[midPoint devel/build]
|===

== Preparation

https://www.vagrantup.com/[Vagrant] is an easy way how to prepare virtual machines quickly,
especially for development or testing purposes.

On Windows, I recommend https://chocolatey.org/[Chocolatey package manager] to install both
https://www.virtualbox.org/[VirtualBox] and Vagrant quickly.

After https://chocolatey.org/install[installing Chocolatey],
it's a matter of two commands in `cmd` (run as administrator, of course):
----
cinst -y virtualbox
cinst -y vagrant
----

== Using the vagrant environment

After that just enter the provided subdirectories, check README file for necessary steps and then run:
----
vagrant up
----

And the magic happens...

*It is not necessary to repeat the preparation steps the next time.*
Just use `vagrant up` and it will start the VM in the state you left it previously.

The first time Vagrant provisions the virtual machine, which means:

* It downloads specified base vagrant box, which typically is some base Linux box.
* It creates VM on the VirtualBox and starts it.
* If some provisioning is necessary, it runs it (typically shell-based in this project).

The first step takes the longest time (download), but after all these are done,
next time you use `vagrant up` it merely starts the existing provisioned VM for you.
This means that any preparation steps need to be done only the first time, or after the box is destroyed.

To stop the box you can either shut it down from inside, or use:
----
vagrant halt
----

To destroy the box (it should remove it also from VirtualBox, you can check that):
----
vagrant destroy -f
----
