= PostgreSQL for midPoint - new repository

Necessary SQL schema files from midpoint sources (repository) are downloaded by Vagrantfile.
If a different version is necessary, modify the `Vagrantfile` accordingly.

To run the environment (first time takes longer):

----
vagrant up
----

And wait... if everything is OK, you can try:

----
vagrant ssh
----

[IMPORTANT]
====
Main reason for this Vagrantbox is testing with new repository - that's what `midpoint` database
is for; for automated tests with new repo there is separate `midtest` database too.
And there is more!
There is also `midaudit` if you wish to use separate audit database.
You don't have to, audit tables are in the main `midpoint` database as well - but you can.

But there is also `midold` database with old repository which is also available with another
Vagrantbox - why is it here?
It's meant for comparison tests on the same "hardware" with the same PG version and setup.
You can ignore it if you're only interested in the new repository.
====

== How to use

JDBC URL is: `jdbc:postgresql://192.168.56.33:5432/midpoint`

Username/password: `midpoint`/`password`

Alternative databases (password is the same as above):

* for automated tests - database and username `midtest`
* old repository for comparison tests - database and username `midold`

IP must match the one from the link:Vagrantfile[].

To run tests with the new repo we need add the following JVM args:
----
-Dtest.config.file=test-config-new-repo.xml
----

If different JDBC URL, username and password is used, they must be provided too using
https://docs.evolveum.com/midpoint/reference/deployment/midpoint-home-directory/overriding-config-xml-parameters/[`config.xml` overriding mechanism].
E.g. for JDBC URL with localhost and different port:
----
-Dmidpoint.repository.jdbcUrl=jdbc:postgresql://localhost:15432
----

Test configuration for old repository can be set using `-Dconfig` JVM argument:
----
-Dconfig=<path-to-vagrantboxes>/vagrant-midpoint-db-pg-native/vagrant-midold.properties
----

Note, that this only works for old repository, use JVM args mentioned before for new repo.

=== Using dedicated midpoint.home directory

To use the new repository for midpoint application it is recommended to pre-create dedicated
`${midpoint.home}` directory for it and copy the provided `config.xml` there.
Then run the midpoint with this JVM argument: `-Dmidpoint.home=<path-to>\midpoint-home-pgnew`
(where `midpoint-home-pgnew` is the actual midPoint home).

== See also

* https://docs.evolveum.com/midpoint/reference/repository/native-postgresql/usage/[Using Native PostgreSQL Repository]
* https://docs.evolveum.com/midpoint/reference/repository/configuration/[Repository Configuration]
* https://docs.evolveum.com/midpoint/reference/repository/generic/postgresql/[Postgres setup for old repository]
