= MariaDB for midPoint

Before running `vagrant up` first create `tmp` directory for non-provided files.

Following files from midpoint sources (repository) go to `tmp` directory (shared with MySQL):

* https://raw.githubusercontent.com/Evolveum/midpoint/master/config/sql/mysql-4.2-all.sql
* https://raw.githubusercontent.com/Evolveum/midpoint/master/repo/repo-sql-impl-test/sql-procedures/mysql.sql

Then run:
----
vagrant up
----

And wait... if everything is OK, you can try:
----
vagrant ssh
----

== How to use

JDBC URL is: `jdbc:mariadb://192.168.56.32:3306/midpoint`

Username/password: `midpoint`/`password`

IP must match the one from the link:Vagrantfile[].

Properties file `vagrant-mariadb.properties` for tests is provided, see comment there how to use it.

Just copy provided `config.xml` (not used by the Vagrant box, actually) to your `${midpoint.home}`.
Alternatively, create a new directory like `midpoint-home-mariadb`, put the `config.xml` there
and run the midpoint with this JVM argument: `-Dmidpoint.home=<path-to>\midpoint-home-mariadb`.

== See also

https://wiki.evolveum.com/display/midPoint/MariaDB
