# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # base Vagrantbox we're starting with
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "mid-mariadb"

  config.vm.box_check_update = false

  # we don't forward ports, we will access this IP directly
  config.vm.network "private_network", ip: "192.168.56.32"


  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
    vb.name = "midpoint-db-mariadb"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    export DEBIAN_FRONTEND="noninteractive"
    sudo debconf-set-selections <<< "mariadb-server mysql-server/root_password password password"
    sudo debconf-set-selections <<< "mariadb-server mysql-server/root_password_again password password"

    sudo apt-get install -y mariadb-server

    # allow connections from outside (not just from localhost)
    sudo ed /etc/mysql/mariadb.conf.d/50-server.cnf << EOF
# we'll find line starting with bind_address
/^bind-address
# and then well insert ('i') this before it (up to '.')
i
#
.
# now we join the next line to it, which effectively comments it out
j
# write the file and finish
wq
EOF
    # change of configuration requires DB restart
    sudo service mysql restart

    # initializing midpoint user, database, etc.
    mysql < /vagrant/create-midpoint-db.sql

    # importing midPoint schema
    mysql midpoint < /vagrant/tmp/mysql-4.2-all.sql
    # importing midPoint cleanup procedure for tests
    mysql midpoint < /vagrant/tmp/mysql.sql

  SHELL
end