# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # base Vagrantbox we're starting with
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "midpoint-dev"

  config.vm.box_check_update = false

  # multiple entries can be added, but we don't need web, and we need 8080 free on host
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.56.50"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
    vb.name = "midpoint-dev"
    # 1G would be too tight for build, OOM possible
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    #sudo apt-get install -y nothing necessary, git is already there
    mkdir tools
    cd tools
    wget https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-linux_x64.tar.gz -qcO - | tar xzv
    wget https://cdn.azul.com/zulu/bin/zulu16.28.11-ca-jdk16.0.0-linux_x64.tar.gz -qcO - | tar xzv
    wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -qcO - | tar xzv
    cd
    
    # configure JAVA_HOMEs, PATH, etc.
    sudo bash -c 'cat >> ~vagrant/.bashrc' << EOF

export TOOLS_HOME=$HOME/tools

function setjava() {
  if [ -z "$1" ]; then
    echo "Version number is from JAVA<version>_HOME. Available Javas:"
    printenv | egrep '^JAVA[^_]+_HOME=' || echo "None? Do something about it!"
    return
  fi
  JAVA_HOME_VAR="JAVA${1}_HOME"
  JAVA_HOME_VAL="${!JAVA_HOME_VAR}"
  if [ -z "$JAVA_HOME_VAL" ]; then
    echo "No value set for $JAVA_HOME_VAR"
    return
  fi

  echo "Using $JAVA_HOME_VAR with value $JAVA_HOME_VAL"
  export JAVA_HOME="$JAVA_HOME_VAL"
  # Now to fix PATH to new JAVA_HOME (TOOLS_HOME is defined in environment)
  PATH="$(echo $PATH |
    sed \
      -e "s%/c/PROGRA~./Java/jdk[^:]*%$JAVA_HOME/bin%gI" \
      -e "s%$TOOLS_HOME/java/[^:]*%$JAVA_HOME/bin%gI")"
  if ! type -p java &> /dev/null; then
    echo "Adding java to PATH"
    PATH=$JAVA_HOME/bin:$PATH
  fi
  java -version
}

export JAVA11_HOME=$HOME/tools/zulu11.45.27-ca-jdk11.0.10-linux_x64
export JAVA16_HOME=$HOME/tools/zulu16.28.11-ca-jdk16.0.0-linux_x64

echo
echo "Use macros \"setjava <version>\" to switch between Javas (JAVA_HOME, PATH)."
setjava ''

echo
setjava 11

PATH=$PATH:$HOME/tools/apache-maven-3.6.3/bin
EOF

  SHELL
end