# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 1521, host: 1521
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.56.31"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "midpoint-oracle-xe"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # update causes breaks guest additions and /vagrant mounting will fail
    #sudo yum -y update

    # installing Oracle packages
    sudo yum -y localinstall /vagrant/tmp/oracle-database-preinstall-*.rpm
    sudo yum -y localinstall /vagrant/tmp/oracle-database-xe-18c-*.rpm

    # configuring the database
    sudo bash -c 'echo "ORACLE_PASSWORD=password" >> /etc/sysconfig/oracle-xe-18c.conf'
    sudo /etc/init.d/oracle-xe-18c configure

    # to enable start of Oracle after boot
    sudo systemctl daemon-reload
    sudo systemctl enable oracle-xe-18c

    # add convenient setup for vagrant
    cat >> ~vagrant/.bash_profile << EOF
export ORACLE_SID=XE
export ORAENV_ASK=NO

. /opt/oracle/product/18c/dbhomeXE/bin/oraenv
EOF

    # this is needed for root to find dbhome
    PATH=$PATH:/usr/local/bin
    # and now to create midpoint schema
    export ORACLE_SID=XE
    export ORAENV_ASK=NO
    . /opt/oracle/product/18c/dbhomeXE/bin/oraenv

    sqlplus -S system/password@localhost/XEPDB1 <<< '@/vagrant/create-midpoint-db.sql'

    # importing midPoint schema
    sqlplus -S midpoint/password@localhost/XEPDB1 <<< "@/vagrant/tmp/oracle-4.2-all.sql"
    # importing midPoint cleanup procedure for tests
    sqlplus -S midpoint/password@localhost/XEPDB1 <<< "@/vagrant/tmp/oracle.sql"

  SHELL
end
